import type { INodeType, INodeTypeDescription } from 'n8n-workflow';

export class Streamline implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Streamline for Shopify',
		name: 'streamline',
		icon: 'file:logo.svg',
		group: ['transform'],
		version: 1,
		usableAsTool: true,
		subtitle: '={{ $parameter.resource === "orderActions" ? ($parameter.operation === "getOne" ? "Get an order" : "Get many orders") : $parameter.resource === "productActions" ? ($parameter.operation === "getOne" ? "Get a product" : $parameter.operation === "getMany" ? "Get many products" : $parameter.operation === "createProduct" ? "Create a product" : $parameter.operation === "createVariant" ? "Create a variant" : $parameter.operation === "updateProduct" ? "Update a product" : $parameter.operation === "updateVariant" ? "Update a variant" : $parameter.operation === "deleteProduct" ? "Delete a product" : $parameter.operation === "deleteVariant" ? "Delete a variant" : $parameter.operation) : $parameter.resource === "additionalActions" ? ($parameter.operation === "getRecommendations" ? "Get AI product recommendations" : $parameter.operation === "getLocations" ? "Get inventory locations" : $parameter.operation === "createDiscount" ? "Create a discount" : $parameter.operation) : $parameter.operation }}',
		description: 'Call Streamline APIs',
		defaults: { name: 'Streamline for Shopify' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'streamlineApi', required: true }],
		requestDefaults: {
			baseURL: 'https://streamline-connector-for-voiceflow.gadget.app',
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
				Authorization: 'Bearer gsk-xGZjqxkDrmeYjdYWGQmpBCcZhFzzNfh2',
			},
		},
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Order', value: 'orderActions' },
					{ name: 'Product', value: 'productActions' },
					{ name: 'Additional', value: 'additionalActions' },
					
					// { name: 'Get Product List', value: 'getProductList' },
					// { name: 'Update Product', value: 'updateProduct' },
					// { name: 'Update Variant', value: 'updateVariant' },
					// { name: 'Update Product Description', value: 'updateProductDescription' },
				],
				default: 'productActions',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['orderActions'] } },
				options: [
					{
						name: 'Get an Order',
						value: 'getOne',
						action: 'Get an order',
						description: 'Get an order using email or order number',
						routing: { request: { method: 'GET', url: '/api/order-data' } },
					},
					{
						name: 'Get Many Orders',
						value: 'getMany',
						action: 'Get many orders',
						description: 'Get paginated list of all orders',
						routing: { request: { method: 'GET', url: '/api/order-data' } },
					},
				],
				default: 'getOne',
			},
			{
				displayName: 'Customer Email',
				description: 'Email of the customer to look up orders for',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: '',
				routing: {
					send: {
						property: 'email',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Order Number',
				description: 'Specific order number to retrieve',
				name: 'orderNumber',
				type: 'string',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: '',
				routing: {
					send: {
						property: 'orderNumber',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Page',
				description: 'Page number (1-based). Use 1 for the first page.',
				name: 'page',
				type: 'number',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 1,
				typeOptions: { minValue: 1, maxValue: 1000 },
				routing: {
					send: { property: 'page', type: 'query' },
				},
			},
			{
				displayName: 'Items per Page',
				description: 'Number of orders per page (max 10 for this endpoint)',
				name: 'size',
				type: 'number',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 10,
				typeOptions: { minValue: 1, maxValue: 10 },
				routing: {
					send: { property: 'size', type: 'query' },
				},
			},
			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 'llm-ready',
				routing: {
					send: { property: 'format', type: 'query' },
				},
			},
			// ---- Additional actions ----
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['additionalActions'] } },
				options: [
					{
						name: 'Get AI Product Recommendations',
						value: 'getRecommendations',
						action: 'Get AI product recommendations',
						description: 'Get AI-based product suggestions',
						routing: { request: { method: 'GET', url: '/products/recommendations' } },
					},
					{
						name: 'Get Inventory Locations',
						value: 'getLocations',
						action: 'Get inventory locations',
						description: 'Retrieve store locations',
						routing: { request: { method: 'GET', url: '/products/locations' } },
					},
					{
						name: 'Create a Discount',
						value: 'createDiscount',
						action: 'Create a discount',
						description: 'Create a new discount code',
						routing: { request: { method: 'POST', url: '/api/create-discount-code' } },
					},
				],
				default: 'getRecommendations',
			},
			{
				displayName: 'Query',
				description: 'Natural language search query for product recommendations',
				required: true,
				name: 'searchQuery',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['getRecommendations'],
					},
				},
				default: '',
				routing: {
					send: {
						property: 'searchQuery',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['getRecommendations'],
					},
				},
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},


			// ---- Product actions ----
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['productActions'] } },
				options: [
					{
						name: 'Create a Product',
						value: 'createProduct',
						action: 'Create a product',
						description: 'Create a new product in your store',
						routing: { request: { method: 'POST', url: '/products/create-product' } },
					},
					{
						name: 'Create a Variant',
						value: 'createVariant',
						action: 'Create a variant',
						description: 'Add new variants to an existing product',
						routing: { request: { method: 'POST', url: '/products/create-variant' } },
					},
					{
						name: 'Delete a Product',
						value: 'deleteProduct',
						action: 'Delete a product',
						description: 'Permanently delete a product',
						routing: { request: { method: 'POST', url: '/products/delete-product' } },
					},
					{
						name: 'Delete a Variant',
						value: 'deleteVariant',
						action: 'Delete a variant',
						description: 'Delete a variant from a product',
						routing: { request: { method: 'POST', url: '/products/delete-variant' } },
					},
					{
						name: 'Get a Product',
						value: 'getOne',
						action: 'Get a product',
						description: 'Get a product by ID or title',
						routing: {
							request: { method: 'GET', url: '/products/inventory' }
						},
					},
					{
						name: 'Get Many Products',
						value: 'getMany',
						action: 'Get many products',
						description: 'Get inventory for all products (by shop)',
						routing: { request: { method: 'GET', url: '/products/inventory' } },
					},
					{
						name: 'Update a Product',
						value: 'updateProduct',
						action: 'Update a product',
						description: 'Update product title, vendor, tags, status, etc',
						routing: { request: { method: 'POST', url: '/products/update-product' } },
					},
					{
						name: 'Update a Variant',
						value: 'updateVariant',
						action: 'Update a variant',
						description: 'Update variant price, SKU, options, etc',
						routing: { request: { method: 'POST', url: '/products/update-variant' } },
					},
				],
				default: 'getOne',
			},
			{
				displayName: 'Look Up By',
				description: 'Search by product ID or product title',
				name: 'searchQuery',
				type: 'options',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
					},
				},
				options: [
					{ name: 'Product ID', value: 'productId' },
					{ name: 'Product Title', value: 'productTitle' },
				],
				default: 'productId',
			},
			{
				displayName: 'Product ID',
				description: 'Numeric ID or Shopify GID (e.g. gid://shopify/Product/123456789)',
				name: 'productId',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
						searchQuery: ['productId'],
					},
				},
				default: '',
				placeholder: '123456789012345 or gid://shopify/Product/123456789',
				routing: {
					send: {
						property: 'productId',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Product Title',
				description: 'Search by product title',
				name: 'productTitle',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
						searchQuery: ['productTitle'],
					},
				},
				default: '',
				placeholder: 'Blue Shirt',
				routing: {
					send: {
						property: 'productTitle',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
					},
				},
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},
			// {
			// 	displayName: 'Shop ID',
			// 	description: 'Shop ID (e.g. 12345)',
			// 	name: 'shopId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: {
			// 		show: {
			// 			resource: ['productActions'],
			// 			operation: ['getMany'],
			// 		},
			// 	},
			// 	default: '',
			// 	placeholder: '12345',
			// 	routing: { send: { property: 'shopId', type: 'query' } },
			// },
			{
				displayName: 'Page',
				description: 'Page number (1-based). Use 1 for the first page.',
				name: 'page',
				type: 'number',
				typeOptions: { minValue: 1 },
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 1,
				routing: { send: { property: 'page', type: 'query' } },
			},
			{
				displayName: 'Size',
				description: 'Number of products per page',
				name: 'size',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 250 },
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 50,
				routing: { send: { property: 'size', type: 'query' } },
			},
			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 'llm-ready',
				routing: { send: { property: 'format', type: 'query' } },
			},

			// ---- Create a Product ----
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop to create the product in.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Title',
				description: 'Product title (required)',
				name: 'title',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				routing: { send: { property: 'title', type: 'body' } },
			},
			{
				displayName: 'Description',
				description: 'Product description (HTML)',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 3 },
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				routing: { send: { property: 'description', type: 'body' } },
			},
			{
				displayName: 'Vendor',
				name: 'vendor',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				routing: { send: { property: 'vendor', type: 'body' } },
			},
			{
				displayName: 'Product Type',
				name: 'productType',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				routing: { send: { property: 'productType', type: 'body' } },
			},
			{
				displayName: 'Tags',
				description: 'Comma-separated or JSON array of tags',
				name: 'tags',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				placeholder: 'summer, cotton',
				routing: { send: { property: 'tags', type: 'body' } },
			},
			{
				displayName: 'Handle',
				description: 'URL handle (defaults from title if omitted)',
				name: 'handle',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				routing: { send: { property: 'handle', type: 'body' } },
			},
			{
				displayName: 'Template Suffix',
				description: 'Theme template for the product page (e.g. custom-product). Maps to Shopify theme template.',
				name: 'templateSuffix',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				placeholder: 'e.g. custom-product',
				routing: { send: { property: 'templateSuffix', type: 'body' } },
			},
			{
				displayName: 'Status',
				description: 'ACTIVE, DRAFT, or ARCHIVED',
				name: 'status',
				type: 'options',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				options: [
					{ name: 'Draft', value: 'DRAFT' },
					{ name: 'Active', value: 'ACTIVE' },
					{ name: 'Archived', value: 'ARCHIVED' },
				],
				default: 'DRAFT',
				routing: { send: { property: 'status', type: 'body' } },
			},
			{
				displayName: 'Product Options',
				description: 'Add option names and comma-separated values (e.g. Size: S, M, L). Max 3 options. Creates variants per option combination.',
				name: 'productOptionsOptions',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
					multipleValueButtonText: 'Add option',
				},
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: {},
				options: [
					{
						displayName: 'Option',
						name: 'option',
						values: [
							{
								displayName: 'Name',
								name: 'name',
								type: 'string',
								default: '',
								placeholder: 'e.g. Size',
							},
							{
								displayName: 'Values',
								name: 'values',
								type: 'string',
								default: '',
								placeholder: 'e.g. S, M, L',
							},
						],
					},
				],
				routing: { send: { property: 'productOptionsOptions', type: 'body' } },
			},
			{
				displayName: 'Product Options (API)',
				name: 'productOptions',
				type: 'hidden',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '={{ (($parameter.productOptionsOptions && $parameter.productOptionsOptions.option) || []).slice(0, 3).map(o => ({ name: String((o.name || "").trim()), values: (typeof o.values === "string" ? o.values.split(",").map(v => v.trim()).filter(Boolean) : (Array.isArray(o.values) ? o.values : [])).map(v => (typeof v === "object" && v && "name" in v ? { name: String(v.name).trim() } : { name: String(v).trim() })) })).filter(o => o.name && o.values.length > 0) }}',
				routing: { send: { property: 'productOptions', type: 'body' } },
			},
			{
				displayName: 'Images',
				description: 'JSON array of image URLs or objects with source/alt',
				name: 'images',
				type: 'string',
				displayOptions: { show: { resource: ['productActions'], operation: ['createProduct'] } },
				default: '',
				placeholder: '["https://example.com/image.jpg"]',
				routing: { send: { property: 'images', type: 'body' } },
			},

			// ---- Create a Variant ----
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop the product belongs to.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['createVariant'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID or numeric ID to add variants to',
				name: 'productId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['createVariant'] } },
				default: '',
				placeholder: 'gid://shopify/Product/123456789012345',
				routing: { send: { property: 'productId', type: 'body' } },
			},
			{
				displayName: 'Variant Fields',
				name: 'variantFields',
				type: 'collection',
				placeholder: 'Add Field',
				displayOptions: { show: { resource: ['productActions'], operation: ['createVariant'] } },
				default: {},
				options: [
					{
						displayName: 'Variants',
						name: 'variants',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
							multipleValueButtonText: 'Add variant',
						},
						default: {},
						description: 'Each variant needs option values (e.g. Size: M) and price',
						options: [
							{
								displayName: 'Variant',
								name: 'variant',
								values: [
									{
										displayName: 'Barcode',
										name: 'barcode',
										type: 'string',
										default: '',
										placeholder: '1234567890123',
									},
									{
										displayName: 'Compare At Price',
										name: 'compareAtPrice',
										type: 'string',
										default: '',
										placeholder: '39.99',
									},
									{
										displayName: 'Cost',
										name: 'cost',
										type: 'string',
										default: '',
										placeholder: '15.00',
									},
									{
										displayName: 'Inventory Policy',
										name: 'inventoryPolicy',
										type: 'options',
										default: 'deny',
										description: 'Deny = do not allow backorders; Continue = allow',
										options: [
											{ name: 'Deny', value: 'deny' },
											{ name: 'Continue', value: 'continue' },
										],
									},
									{
										displayName: 'Media URLs',
										name: 'mediaSrc',
										type: 'string',
										default: '',
										description: 'JSON array of image URLs to attach to this variant',
										placeholder: '["https://cdn.shopify.com/..."]',
									},
									{
										displayName: 'Option Values',
										name: 'optionValues',
										type: 'fixedCollection',
										typeOptions: {
											multipleValues: true,
											multipleValueButtonText: 'Add option',
										},
										default: {},
										description: 'Match product options (e.g. Size, Color)',
										options: [
											{
												displayName: 'Option',
												name: 'option',
												values: [
													{
														displayName: 'Option Name',
														name: 'optionName',
														type: 'string',
														default: '',
														placeholder: 'e.g. Size',
													},
													{
														displayName: 'Value',
														name: 'name',
														type: 'string',
														default: '',
														placeholder: 'e.g. M',
													},
												],
											},
										],
									},
									{
										displayName: 'Price',
										name: 'price',
										type: 'string',
										required: true,
										default: '',
										description: 'Variant price',
										placeholder: '29.99',
									},
									{
										displayName: 'Quantity Adjustments',
										name: 'quantityAdjustments',
										type: 'fixedCollection',
										typeOptions: {
											multipleValues: true,
											multipleValueButtonText: 'Add location',
										},
										default: {},
										description: 'Set inventory quantity per location',
										options: [
											{
												displayName: 'Adjustment',
												name: 'adjustment',
												values: [
													{
														displayName: 'Location ID',
														name: 'locationId',
														type: 'string',
														default: '',
														placeholder: 'gid://shopify/Location/123',
													},
													{
														displayName: 'Quantity',
														name: 'adjustment',
														type: 'number',
														default: 0,
														description: 'Quantity to set or adjust at this location',
														typeOptions: { minValue: -999999, maxValue: 999999 },
													},
												],
											},
										],
									},
									{
										displayName: 'SKU',
										name: 'sku',
										type: 'string',
										default: '',
										placeholder: 'TSH-M',
									},
									{
										displayName: 'Taxable',
										name: 'taxable',
										type: 'boolean',
										default: true,
										description: 'Whether this variant is taxable',
									},
								],
							},
						],
					},
				],
				routing: { send: { property: 'variantFields', type: 'body' } },
			},
			{
				displayName: 'Strategy',
				description: 'How to handle the product’s existing single variant when adding new variants. Default: remove only the standard "Default Title" variant; Remove Standalone Variant: remove any single variant (default or custom) so your new variants replace it.',
				name: 'strategy',
				type: 'options',
				displayOptions: { show: { resource: ['productActions'], operation: ['createVariant'] } },
				options: [
					{ name: 'Default', value: 'DEFAULT', description: 'Remove the "Default Title" variant if it’s the only one; keep custom standalone variants' },
					{ name: 'Remove Standalone Variant', value: 'REMOVE_STANDALONE_VARIANT', description: 'Remove the existing single variant (any type) so new variants replace it' },
				],
				default: 'DEFAULT',
				routing: { send: { property: 'strategy', type: 'body' } },
			},

			// ---- Update a Product ----
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop the product belongs to.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['updateProduct'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID or numeric ID to update',
				name: 'productId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['updateProduct'] } },
				default: '',
				routing: { send: { property: 'productId', type: 'body' } },
			},
			{
				displayName: 'Update Fields',
				name: 'updateFields',
				type: 'collection',
				placeholder: 'Add Field',
				displayOptions: { show: { resource: ['productActions'], operation: ['updateProduct'] } },
				default: {},
				options: [
					{
						displayName: 'Body HTML',
						name: 'description',
						type: 'string',
						typeOptions: { rows: 3 },
						default: '',
						description: 'Product description (HTML). Leave empty to leave unchanged.',
						placeholder: '<p>Product description</p>',
					},
					{
						displayName: 'Handle',
						name: 'handle',
						type: 'string',
						default: '',
						description: 'Unique URL handle for the product',
					},
					{
						displayName: 'Images',
						name: 'images',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
							multipleValueButtonText: 'Add image',
						},
						default: {},
						description: 'Add or replace product images. Use Position 1 to replace the 1st image, 2 for the 2nd, etc. Use 0 to add a new image at the end.',
						options: [
							{
								displayName: 'Image',
								name: 'image',
								values: [
									{
										displayName: 'Position (1=1st Image, 2=2nd…; 0=Add at End)',
										name: 'position',
										type: 'number',
										default: 0,
										description: 'Replace: 1 = first image, 2 = second, etc. Add at end: 0 or leave empty.',
										placeholder: '1 to replace 1st image, 0 to add',
										typeOptions: { minValue: 0 },
									},
									{
										displayName: 'Image Source',
										name: 'source',
										type: 'string',
										default: '',
										description: 'Image URL',
										placeholder: 'https://cdn.shopify.com/...',
									},
								],
							},
						],
					},
					{
						displayName: 'Options',
						name: 'productOptionsOptions',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
							multipleValueButtonText: 'Add option',
						},
						default: {},
						description: 'Update product options (e.g. Size, Color). First option in list is applied.',
						options: [
							{
								displayName: 'Option',
								name: 'option',
								values: [
									{
										displayName: 'Name',
										description: 'Option name to update (e.g. Size). Must match existing option.',
										name: 'name',
										type: 'string',
										default: '',
										placeholder: 'e.g. Size',
									},
									{
										displayName: 'Values',
										description: 'Comma-separated values to set for this option',
										name: 'values',
										type: 'string',
										default: '',
										placeholder: 'e.g. S, M, L',
									},
								],
							},
						],
					},
					{
						displayName: 'Product Type',
						name: 'productType',
						type: 'string',
						default: '',
						description: 'Product type for filtering and search',
					},
					{
						displayName: 'Published At',
						name: 'publishedAt',
						type: 'options',
						default: 'active',
						description: 'Active, draft, or archived',
						options: [
							{ name: 'Active', value: 'active' },
							{ name: 'Archived', value: 'archived' },
							{ name: 'Draft', value: 'draft' },
						],
					},
					{
						displayName: 'Tags',
						name: 'tags',
						type: 'string',
						default: '',
						description: 'Comma-separated or JSON array. Replaces all tags; use [] to clear.',
					},
					{
						displayName: 'Template Suffix',
						name: 'templateSuffix',
						type: 'string',
						default: '',
						description: 'Theme template for the product page (e.g. custom-product)',
						placeholder: 'e.g. custom-product',
					},
					{
						displayName: 'Title',
						name: 'title',
						type: 'string',
						default: '',
						description: 'Product title',
					},
					{
						displayName: 'Vendor',
						name: 'vendor',
						type: 'string',
						default: '',
						description: "Product vendor name",
					},
				],
				routing: { send: { property: 'updateFields', type: 'body' } },
			},
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop the product belongs to.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteProduct'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID or numeric ID to delete',
				name: 'productId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteProduct'] } },
				default: '',
				placeholder: 'gid://shopify/Product/123456789012345',
				routing: { send: { property: 'productId', type: 'body' } },
			},
			{
				displayName: 'Synchronous',
				description: 'Whether to wait for Shopify to complete deletion before returning the response',
				name: 'synchronous',
				type: 'boolean',
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteProduct'] } },
				default: true,
				routing: { send: { property: 'synchronous', type: 'body' } },
			},

			// ---- Update a Variant ----
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop the variant belongs to.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['updateVariant'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Variant ID',
				description: 'Shopify variant GID or numeric ID to update',
				name: 'variantId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['updateVariant'] } },
				default: '',
				routing: { send: { property: 'variantId', type: 'body' } },
			},
			{
				displayName: 'Update Fields',
				name: 'updateFields',
				type: 'collection',
				placeholder: 'Add Field',
				displayOptions: { show: { resource: ['productActions'], operation: ['updateVariant'] } },
				default: {},
				options: [
					{
						displayName: 'Barcode',
						name: 'barcode',
						type: 'string',
						default: '',
						placeholder: '1234567890123',
					},
					{
						displayName: 'Compare At Price',
						name: 'compareAtPrice',
						type: 'string',
						default: '',
						placeholder: '39.99',
					},
					{
						displayName: 'Cost',
						name: 'cost',
						type: 'string',
						default: '',
						placeholder: '15.00',
					},
					{
						displayName: 'Inventory Policy',
						name: 'inventoryPolicy',
						type: 'options',
						default: 'deny',
						description: 'Sell when out of stock: Deny = No; Continue = Yes',
						options: [
							{ name: 'Deny', value: 'deny' },
							{ name: 'Continue', value: 'continue' },
						],
					},
					{
						displayName: 'Media URLs',
						name: 'mediaSrc',
						type: 'string',
						default: '',
						description: 'One image URL or a JSON array of URLs to add to this variant (e.g. https://cdn.shopify.com/... or ["https://...", "https://..."]).',
						placeholder: 'https://cdn.shopify.com/... or ["https://..."]',
					},
					{
						displayName: 'Price',
						name: 'price',
						type: 'string',
						default: '',
						placeholder: '29.99',
					},
					{
						displayName: 'Quantity Adjustments',
						name: 'quantityAdjustments',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
							multipleValueButtonText: 'Add location',
						},
						default: {},
						description: 'Set inventory quantity per location',
						options: [
							{
								displayName: 'Adjustment',
								name: 'adjustment',
								values: [
									{
										displayName: 'Location ID',
										name: 'locationId',
										type: 'string',
										default: '',
										placeholder: 'gid://shopify/Location/123',
									},
									{
										displayName: 'Quantity',
										name: 'adjustment',
										type: 'number',
										default: 0,
										description: 'Quantity to set or adjust at this location',
										typeOptions: { minValue: -999999, maxValue: 999999 },
									},
								],
							},
						],
					},
					{
						displayName: 'SKU',
						name: 'sku',
						type: 'string',
						default: '',
						placeholder: 'TSH-M',
					},
					{
						displayName: 'Taxable',
						name: 'taxable',
						type: 'boolean',
						default: true,
						description: 'Whether this variant is taxable',
					},
				],
				routing: { send: { property: 'updateFields', type: 'body' } },
			},
			{
				displayName: 'Shop ID',
				description: 'Shop ID (required). The Shopify shop the product belongs to.',
				name: 'shopId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteVariant'] } },
				default: '',
				placeholder: 'e.g. 86025044251',
				routing: { send: { property: 'shopId', type: 'body' } },
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID or numeric ID that owns the variant',
				name: 'productId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteVariant'] } },
				default: '',
				placeholder: 'gid://shopify/Product/123456789012345',
				routing: { send: { property: 'productId', type: 'body' } },
			},
			{
				displayName: 'Variant ID',
				description: 'Shopify variant GID or numeric ID to delete',
				name: 'variantId',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['productActions'], operation: ['deleteVariant'] } },
				default: '',
				placeholder: 'gid://shopify/ProductVariant/123456789012345',
				routing: { send: { property: 'variantId', type: 'body' } },
			},

			// ---- Get Product List ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['getProductList'] } },
			// 	options: [
			// 		{
			// 			name: 'List Products',
			// 			value: 'get',
			// 			action: 'List products (catalog)',
			// 			description: 'Get paginated product catalog',
			// 			routing: { request: { method: 'GET', url: '/api/product-list' } },
			// 		},
			// 	],
			// 	default: 'get',
			// },
			// {
			// 	displayName: 'Limit',
			// 	description: 'Maximum number of products to return',
			// 	name: 'limit',
			// 	type: 'number',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: 50,
			// 	typeOptions: { minValue: 1, maxValue: 250 },
			// 	routing: { send: { property: 'limit', type: 'query' } },
			// },
			// {
			// 	displayName: 'After Cursor',
			// 	description: 'Optional. Use endCursor from the previous response to fetch the next page. Leave empty for the first page.',
			// 	name: 'after',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: '',
			// 	routing: { send: { property: 'after', type: 'query' } },
			// },
			// {
			// 	displayName: 'Before Cursor',
			// 	description: 'Optional. Use startCursor from the previous response to fetch the previous page. Leave empty for the first request.',
			// 	name: 'before',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: '',
			// 	routing: { send: { property: 'before', type: 'query' } },
			// },


			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['getLocations'] } },
				default: 'llm-ready',
				routing: { send: { property: 'format', type: 'query' } },
			},
			{
				displayName: 'Title',
				description: 'Discount title (e.g. "Summer Sale")',
				name: 'title',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'title', type: 'query' } },
			},
			{
				displayName: 'Code',
				description: 'The discount code string (e.g. SAVE20)',
				name: 'code',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'code', type: 'query' } },
			},
			{
				displayName: 'Customer Gets - Percentage(0 ~ 1)',
				description: 'Numeric value (e.g. 0.2 for 20%)',
				name: 'customerGetsValueNumber',
				type: 'number',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: 0,
			},
			{
				displayName: 'Customer Gets - Items',
				description: 'Apply discount to all items or a single product',
				name: 'customerGetsItems',
				type: 'options',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Single Product', value: 'singleProduct' },
				],
				default: 'all',
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID (e.g. gid://shopify/Product/123456789012345)',
				name: 'customerGetsProductId',
				type: 'string',
				// required: true,
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['create'],
						customerGetsItems: ['singleProduct'],
					},
				},
				default: '',
				placeholder: 'gid://shopify/Product/123456789012345',
			},
			{
				displayName: 'Customer Gets (Value)',
				name: 'customerGetsValue',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '={{ { percentage: Number($parameter.customerGetsValueNumber) || 0 } }}',
				routing: { send: { property: 'customerGets.value', type: 'body' } },
			},
			{
				displayName: 'Customer Gets (Items)',
				name: 'customerGetsItemsBody',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '={{ $parameter.customerGetsItems === "singleProduct" && $parameter.customerGetsProductId ? { products: { productsToAdd: ["gid://shopify/Product/" + $parameter.customerGetsProductId] } } : { all: true } }}',
				routing: { send: { property: 'customerGets.items', type: 'body' } },
			},
			{
				displayName: 'Starts At',
				description: 'ISO date when the discount becomes active',
				name: 'startsAt',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				placeholder: '2025-01-01T00:00:00Z',
				routing: { send: { property: 'startsAt', type: 'query' } },
			},
			{
				displayName: 'Ends At',
				description: 'ISO date when the discount ends (optional)',
				name: 'endsAt',
				type: 'string',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'endsAt', type: 'query' } },
			},
			{
				displayName: 'Usage Limit',
				description: 'Max number of times the code can be used (optional)',
				name: 'usageLimit',
				type: 'number',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: 0,
				routing: { send: { property: 'usageLimit', type: 'query' } },
			},
			{
				displayName: 'Applies Once Per Customer',
				description: 'Whether the discount applies only once per customer',
				name: 'appliesOncePerCustomer',
				type: 'boolean',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: false,
				routing: { send: { property: 'appliesOncePerCustomer', type: 'query' } },
			},


			// ---- Update Product ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateProduct'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update product',
			// 			description: 'Update product title, vendor, tags, status, etc.',
			// 			routing: { request: { method: 'GET', url: '/products/update-product' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Product ID',
			// 	description: 'Shopify product GID or numeric ID',
			// 	name: 'productId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productId', type: 'query' } },
			// },
			// {
			// 	displayName: 'Title',
			// 	description: 'Product title',
			// 	name: 'title',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'title', type: 'query' } },
			// },
			// {
			// 	displayName: 'Vendor',
			// 	name: 'vendor',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'vendor', type: 'query' } },
			// },
			// {
			// 	displayName: 'Product Type',
			// 	name: 'productType',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productType', type: 'query' } },
			// },
			// {
			// 	displayName: 'Tags',
			// 	description: 'Comma-separated tags',
			// 	name: 'tags',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'tags', type: 'query' } },
			// },
			// {
			// 	displayName: 'Status',
			// 	description: 'ACTIVE, DRAFT, or ARCHIVED',
			// 	name: 'status',
			// 	type: 'options',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	options: [
			// 		{ name: 'Active', value: 'ACTIVE' },
			// 		{ name: 'Draft', value: 'DRAFT' },
			// 		{ name: 'Archived', value: 'ARCHIVED' },
			// 	],
			// 	default: '',
			// 	routing: { send: { property: 'status', type: 'query' } },
			// },
			// {
			// 	displayName: 'Handle',
			// 	name: 'handle',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'handle', type: 'query' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'query' } },
			// },



			// ---- Update Variant ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateVariant'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update variant',
			// 			description: 'Update variant price, SKU, options, etc.',
			// 			routing: { request: { method: 'GET', url: '/products/update-variant' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Variant ID',
			// 	description: 'Shopify variant GID or numeric ID',
			// 	name: 'variantId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'variantId', type: 'query' } },
			// },
			// {
			// 	displayName: 'Title',
			// 	name: 'title',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'title', type: 'query' } },
			// },
			// {
			// 	displayName: 'Price',
			// 	name: 'price',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'price', type: 'query' } },
			// },
			// {
			// 	displayName: 'Compare At Price',
			// 	name: 'compareAtPrice',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'compareAtPrice', type: 'query' } },
			// },
			// {
			// 	displayName: 'SKU',
			// 	name: 'sku',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'sku', type: 'query' } },
			// },
			// {
			// 	displayName: 'Barcode',
			// 	name: 'barcode',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'barcode', type: 'query' } },
			// },
			// {
			// 	displayName: 'Inventory Policy',
			// 	description: 'deny or continue',
			// 	name: 'inventoryPolicy',
			// 	type: 'options',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	options: [
			// 		{ name: 'Deny', value: 'deny' },
			// 		{ name: 'Continue', value: 'continue' },
			// 	],
			// 	default: '',
			// 	routing: { send: { property: 'inventoryPolicy', type: 'query' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'query' } },
			// },





			// ---- Update Product Description ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update product description',
			// 			description: 'Update product body HTML description',
			// 			routing: { request: { method: 'POST', url: '/products/update-product-description' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Product ID',
			// 	description: 'Shopify product GID or numeric ID',
			// 	name: 'productId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productId', type: 'body' } },
			// },
			// {
			// 	displayName: 'Description',
			// 	description: 'Product description (HTML supported)',
			// 	name: 'description',
			// 	type: 'string',
			// 	typeOptions: { rows: 4 },
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'description', type: 'body' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'body' } },
			// },
		],
	};
}
