import type { INodeType, INodeTypeDescription } from 'n8n-workflow';

export class Streamline implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Streamline for Shopify',
		name: 'streamline',
		icon: 'file:logo.svg',
		group: ['transform'],
		version: 1,
		usableAsTool: true,
		subtitle: '={{ $parameter.resource === "orderActions" ? ($parameter.operation === "getOne" ? "Get an order" : "Get many orders") : $parameter.resource === "productActions" ? ($parameter.operation === "getOne" ? "Get a product" : "Get many products") : $parameter.resource === "additionalActions" ? ($parameter.operation === "getRecommendations" ? "Get AI product recommendations" : $parameter.operation === "getLocations" ? "Get inventory locations" : $parameter.operation === "createDiscount" ? "Create a discount" : $parameter.operation) : $parameter.operation }}',
		description: 'Call Streamline APIs',
		defaults: { name: 'Streamline for Shopify' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'streamlineApi', required: true }],
		requestDefaults: {
			baseURL: 'https://streamline-connector-for-voiceflow.gadget.app',
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
				Authorization: 'Bearer gsk-xGZjqxkDrmeYjdYWGQmpBCcZhFzzNfh2',
			},
		},
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Order', value: 'orderActions' },
					{ name: 'Product', value: 'productActions' },
					{ name: 'Additional', value: 'additionalActions' },
					
					// { name: 'Get Product List', value: 'getProductList' },
					// { name: 'Update Product', value: 'updateProduct' },
					// { name: 'Update Variant', value: 'updateVariant' },
					// { name: 'Update Product Description', value: 'updateProductDescription' },
				],
				default: 'productActions',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['orderActions'] } },
				options: [
					{
						name: 'Get an Order',
						value: 'getOne',
						action: 'Get an order',
						description: 'Get an order using email or order number',
						routing: { request: { method: 'GET', url: '/api/order-data' } },
					},
					{
						name: 'Get Many Orders',
						value: 'getMany',
						action: 'Get many orders',
						description: 'Get paginated list of all orders',
						routing: { request: { method: 'GET', url: '/api/order-data' } },
					},
				],
				default: 'getOne',
			},
			{
				displayName: 'Customer Email',
				description: 'Email of the customer to look up orders for',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: '',
				routing: {
					send: {
						property: 'email',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Order Number',
				description: 'Specific order number to retrieve',
				name: 'orderNumber',
				type: 'string',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: '',
				routing: {
					send: {
						property: 'orderNumber',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getOne'] } },
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Page',
				description: 'Page number (1-based). Use 1 for the first page.',
				name: 'page',
				type: 'number',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 1,
				typeOptions: { minValue: 1, maxValue: 1000 },
				routing: {
					send: { property: 'page', type: 'query' },
				},
			},
			{
				displayName: 'Items per Page',
				description: 'Number of orders per page (max 10 for this endpoint)',
				name: 'size',
				type: 'number',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 10,
				typeOptions: { minValue: 1, maxValue: 10 },
				routing: {
					send: { property: 'size', type: 'query' },
				},
			},
			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['orderActions'], operation: ['getMany'] } },
				default: 'llm-ready',
				routing: {
					send: { property: 'format', type: 'query' },
				},
			},
			// ---- Additional actions ----
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['additionalActions'] } },
				options: [
					{
						name: 'Get AI Product Recommendations',
						value: 'getRecommendations',
						action: 'Get AI product recommendations',
						description: 'Get AI-based product suggestions',
						routing: { request: { method: 'GET', url: '/products/recommendations' } },
					},
					{
						name: 'Get Inventory Locations',
						value: 'getLocations',
						action: 'Get inventory locations',
						description: 'Retrieve store locations',
						routing: { request: { method: 'GET', url: '/products/locations' } },
					},
					{
						name: 'Create a Discount',
						value: 'createDiscount',
						action: 'Create a discount',
						description: 'Create a new discount code',
						routing: { request: { method: 'POST', url: '/api/create-discount-code' } },
					},
				],
				default: 'getRecommendations',
			},
			{
				displayName: 'Query',
				description: 'Natural language search query for product recommendations',
				required: true,
				name: 'searchQuery',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['getRecommendations'],
					},
				},
				default: '',
				routing: {
					send: {
						property: 'searchQuery',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['getRecommendations'],
					},
				},
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},


			// ---- Product actions ----
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['productActions'] } },
				options: [
					{
						name: 'Get a Product',
						value: 'getOne',
						action: 'Get a product',
						description: 'Get a product by ID or title',
						routing: {
							request: { method: 'GET', url: '/products/inventory' }
						},
					},
					{
						name: 'Get Many Products',
						value: 'getMany',
						action: 'Get many products',
						description: 'Get inventory for all products (by shop)',
						routing: { request: { method: 'GET', url: '/products/inventory' } },
					},
				],
				default: 'getOne',
			},
			{
				displayName: 'Look Up By',
				description: 'Search by product ID or product title',
				name: 'searchQuery',
				type: 'options',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
					},
				},
				options: [
					{ name: 'Product ID', value: 'productId' },
					{ name: 'Product Title', value: 'productTitle' },
				],
				default: 'productId',
			},
			{
				displayName: 'Product ID',
				description: 'Numeric ID or Shopify GID (e.g. gid://shopify/Product/123456789)',
				name: 'productId',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
						searchQuery: ['productId'],
					},
				},
				default: '',
				placeholder: '123456789012345 or gid://shopify/Product/123456789',
				routing: {
					send: {
						property: 'productId',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Product Title',
				description: 'Search by product title',
				name: 'productTitle',
				type: 'string',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
						searchQuery: ['productTitle'],
					},
				},
				default: '',
				placeholder: 'Blue Shirt',
				routing: {
					send: {
						property: 'productTitle',
						type: 'query',
					},
				},
			},
			{
				displayName: 'Format',
				description: 'The format of the response. Choose either LLM enriched data or RAW.',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getOne'],
					},
				},
				default: 'llm-ready',
				routing: {
					send: {
						property: 'format',
						type: 'query',
					},
				},
			},
			// {
			// 	displayName: 'Shop ID',
			// 	description: 'Shop ID (e.g. 12345)',
			// 	name: 'shopId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: {
			// 		show: {
			// 			resource: ['productActions'],
			// 			operation: ['getMany'],
			// 		},
			// 	},
			// 	default: '',
			// 	placeholder: '12345',
			// 	routing: { send: { property: 'shopId', type: 'query' } },
			// },
			{
				displayName: 'Page',
				description: 'Page number (1-based). Use 1 for the first page.',
				name: 'page',
				type: 'number',
				typeOptions: { minValue: 1 },
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 1,
				routing: { send: { property: 'page', type: 'query' } },
			},
			{
				displayName: 'Size',
				description: 'Number of products per page',
				name: 'size',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 250 },
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 50,
				routing: { send: { property: 'size', type: 'query' } },
			},
			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: {
					show: {
						resource: ['productActions'],
						operation: ['getMany'],
					},
				},
				default: 'llm-ready',
				routing: { send: { property: 'format', type: 'query' } },
			},

			// ---- Get Product List ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['getProductList'] } },
			// 	options: [
			// 		{
			// 			name: 'List Products',
			// 			value: 'get',
			// 			action: 'List products (catalog)',
			// 			description: 'Get paginated product catalog',
			// 			routing: { request: { method: 'GET', url: '/api/product-list' } },
			// 		},
			// 	],
			// 	default: 'get',
			// },
			// {
			// 	displayName: 'Limit',
			// 	description: 'Maximum number of products to return',
			// 	name: 'limit',
			// 	type: 'number',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: 50,
			// 	typeOptions: { minValue: 1, maxValue: 250 },
			// 	routing: { send: { property: 'limit', type: 'query' } },
			// },
			// {
			// 	displayName: 'After Cursor',
			// 	description: 'Optional. Use endCursor from the previous response to fetch the next page. Leave empty for the first page.',
			// 	name: 'after',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: '',
			// 	routing: { send: { property: 'after', type: 'query' } },
			// },
			// {
			// 	displayName: 'Before Cursor',
			// 	description: 'Optional. Use startCursor from the previous response to fetch the previous page. Leave empty for the first request.',
			// 	name: 'before',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['getProductList'], operation: ['get'] } },
			// 	default: '',
			// 	routing: { send: { property: 'before', type: 'query' } },
			// },


			{
				displayName: 'Format',
				name: 'format',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['getLocations'] } },
				default: 'llm-ready',
				routing: { send: { property: 'format', type: 'query' } },
			},
			{
				displayName: 'Title',
				description: 'Discount title (e.g. "Summer Sale")',
				name: 'title',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'title', type: 'query' } },
			},
			{
				displayName: 'Code',
				description: 'The discount code string (e.g. SAVE20)',
				name: 'code',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'code', type: 'query' } },
			},
			{
				displayName: 'Customer Gets - Percentage(0 ~ 1)',
				description: 'Numeric value (e.g. 0.2 for 20%)',
				name: 'customerGetsValueNumber',
				type: 'number',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: 0,
			},
			{
				displayName: 'Customer Gets - Items',
				description: 'Apply discount to all items or a single product',
				name: 'customerGetsItems',
				type: 'options',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Single Product', value: 'singleProduct' },
				],
				default: 'all',
			},
			{
				displayName: 'Product ID',
				description: 'Shopify product GID (e.g. gid://shopify/Product/123456789012345)',
				name: 'customerGetsProductId',
				type: 'string',
				// required: true,
				displayOptions: {
					show: {
						resource: ['additionalActions'],
						operation: ['create'],
						customerGetsItems: ['singleProduct'],
					},
				},
				default: '',
				placeholder: 'gid://shopify/Product/123456789012345',
			},
			{
				displayName: 'Customer Gets (Value)',
				name: 'customerGetsValue',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '={{ { percentage: Number($parameter.customerGetsValueNumber) || 0 } }}',
				routing: { send: { property: 'customerGets.value', type: 'body' } },
			},
			{
				displayName: 'Customer Gets (Items)',
				name: 'customerGetsItemsBody',
				type: 'hidden',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '={{ $parameter.customerGetsItems === "singleProduct" && $parameter.customerGetsProductId ? { products: { productsToAdd: ["gid://shopify/Product/" + $parameter.customerGetsProductId] } } : { all: true } }}',
				routing: { send: { property: 'customerGets.items', type: 'body' } },
			},
			{
				displayName: 'Starts At',
				description: 'ISO date when the discount becomes active',
				name: 'startsAt',
				type: 'string',
				required: true,
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				placeholder: '2025-01-01T00:00:00Z',
				routing: { send: { property: 'startsAt', type: 'query' } },
			},
			{
				displayName: 'Ends At',
				description: 'ISO date when the discount ends (optional)',
				name: 'endsAt',
				type: 'string',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: '',
				routing: { send: { property: 'endsAt', type: 'query' } },
			},
			{
				displayName: 'Usage Limit',
				description: 'Max number of times the code can be used (optional)',
				name: 'usageLimit',
				type: 'number',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: 0,
				routing: { send: { property: 'usageLimit', type: 'query' } },
			},
			{
				displayName: 'Applies Once Per Customer',
				description: 'Whether the discount applies only once per customer',
				name: 'appliesOncePerCustomer',
				type: 'boolean',
				displayOptions: { show: { resource: ['additionalActions'], operation: ['createDiscount'] } },
				default: false,
				routing: { send: { property: 'appliesOncePerCustomer', type: 'query' } },
			},


			// ---- Update Product ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateProduct'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update product',
			// 			description: 'Update product title, vendor, tags, status, etc.',
			// 			routing: { request: { method: 'GET', url: '/products/update-product' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Product ID',
			// 	description: 'Shopify product GID or numeric ID',
			// 	name: 'productId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productId', type: 'query' } },
			// },
			// {
			// 	displayName: 'Title',
			// 	description: 'Product title',
			// 	name: 'title',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'title', type: 'query' } },
			// },
			// {
			// 	displayName: 'Vendor',
			// 	name: 'vendor',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'vendor', type: 'query' } },
			// },
			// {
			// 	displayName: 'Product Type',
			// 	name: 'productType',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productType', type: 'query' } },
			// },
			// {
			// 	displayName: 'Tags',
			// 	description: 'Comma-separated tags',
			// 	name: 'tags',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'tags', type: 'query' } },
			// },
			// {
			// 	displayName: 'Status',
			// 	description: 'ACTIVE, DRAFT, or ARCHIVED',
			// 	name: 'status',
			// 	type: 'options',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	options: [
			// 		{ name: 'Active', value: 'ACTIVE' },
			// 		{ name: 'Draft', value: 'DRAFT' },
			// 		{ name: 'Archived', value: 'ARCHIVED' },
			// 	],
			// 	default: '',
			// 	routing: { send: { property: 'status', type: 'query' } },
			// },
			// {
			// 	displayName: 'Handle',
			// 	name: 'handle',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'handle', type: 'query' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateProduct'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'query' } },
			// },



			// ---- Update Variant ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateVariant'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update variant',
			// 			description: 'Update variant price, SKU, options, etc.',
			// 			routing: { request: { method: 'GET', url: '/products/update-variant' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Variant ID',
			// 	description: 'Shopify variant GID or numeric ID',
			// 	name: 'variantId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'variantId', type: 'query' } },
			// },
			// {
			// 	displayName: 'Title',
			// 	name: 'title',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'title', type: 'query' } },
			// },
			// {
			// 	displayName: 'Price',
			// 	name: 'price',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'price', type: 'query' } },
			// },
			// {
			// 	displayName: 'Compare At Price',
			// 	name: 'compareAtPrice',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'compareAtPrice', type: 'query' } },
			// },
			// {
			// 	displayName: 'SKU',
			// 	name: 'sku',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'sku', type: 'query' } },
			// },
			// {
			// 	displayName: 'Barcode',
			// 	name: 'barcode',
			// 	type: 'string',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'barcode', type: 'query' } },
			// },
			// {
			// 	displayName: 'Inventory Policy',
			// 	description: 'deny or continue',
			// 	name: 'inventoryPolicy',
			// 	type: 'options',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	options: [
			// 		{ name: 'Deny', value: 'deny' },
			// 		{ name: 'Continue', value: 'continue' },
			// 	],
			// 	default: '',
			// 	routing: { send: { property: 'inventoryPolicy', type: 'query' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateVariant'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'query' } },
			// },





			// ---- Update Product Description ----
			// {
			// 	displayName: 'Operation',
			// 	name: 'operation',
			// 	type: 'options',
			// 	noDataExpression: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'] } },
			// 	options: [
			// 		{
			// 			name: 'Update',
			// 			value: 'update',
			// 			action: 'Update product description',
			// 			description: 'Update product body HTML description',
			// 			routing: { request: { method: 'POST', url: '/products/update-product-description' } },
			// 		},
			// 	],
			// 	default: 'update',
			// },
			// {
			// 	displayName: 'Product ID',
			// 	description: 'Shopify product GID or numeric ID',
			// 	name: 'productId',
			// 	type: 'string',
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'productId', type: 'body' } },
			// },
			// {
			// 	displayName: 'Description',
			// 	description: 'Product description (HTML supported)',
			// 	name: 'description',
			// 	type: 'string',
			// 	typeOptions: { rows: 4 },
			// 	required: true,
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: '',
			// 	routing: { send: { property: 'description', type: 'body' } },
			// },
			// {
			// 	displayName: 'Format',
			// 	name: 'format',
			// 	type: 'hidden',
			// 	displayOptions: { show: { resource: ['updateProductDescription'], operation: ['update'] } },
			// 	default: 'llm-ready',
			// 	routing: { send: { property: 'format', type: 'body' } },
			// },
		],
	};
}
